CREATE TYPE session_status as ENUM(
    'PRE_START',
    'ONGOING',
    'ON_HOLD',
    'ENDED'
);

CREATE TYPE ended_reason as ENUM(
    'NORMAL',
    'EXPIRED',
    'ABANDONED'
);

CREATE TYPE event_type as ENUM(
    'SESSION_CREATED',
    'SESSION_JOINED',
    'CODE_CHANGED',
    'CURSOR_MOVED',
    'CODE_HIGHLIGHTED',
    'LANGUAGE_CHANGED',
    'PROBLEM_SET',
    'GUEST_DISCONNECTED',
    'GUEST_RECONNECTED',
    'GUEST_TOKEN_EXPIRED',
    'GUEST_LEFT',
    'INTERVIEWER_DISCONNECTED',
    'INTERVIEWER_RECONNECTED',
    'SESSION_ENDED',
    'SESSION_ABANDONED',
    'SESSION_EXPIRED'
);

CREATE TYPE user_role as ENUM(
    'INTERVIEWER',
    'GUEST'
);

